SELECT 
LOAN_ID,
date_trunc('month',to_date(cs.ORIGINATION_DATE)) AS vintage,
PAYOFF_DATE,
case when subvention_id is not null then 1 else 0 end as SUBVENTION_FLAG,
CASE
    WHEN bi.MERCHANT_CURRENCY = 'USD' THEN 'USA'
    WHEN bi.MERCHANT_CURRENCY = 'CAD' THEN 'CAN'
END COUNTRY,
CASE
    WHEN pc.VERTICAL_L1 IN ('Air','Cruise','Package')
        THEN pc.VERTICAL_L1
    ELSE 'Other'
END AS VERTICAL,
FICO,
CASE
    WHEN cs.FICO < 640
        THEN 'SubPrime'
    WHEN cs.FICO >= 640
        AND cs.FICO <= 710
        THEN 'NearPrime'
    WHEN cs.FICO > 710
        THEN 'Prime'
END AS CREDIT_SEGMENT,
LOAN_GROUP_NO,
APR,
ORIGINAL_INTEREST_RATE,
ORIGINAL_TERM_TO_MATURITY,
LOAN_STATUS,
ORDER_AMOUNT,
LOAN_AMOUNT,
PRINCIPAL_BALANCE,
CHARGEOFF_PRINCIPAL,
ORIGFEE
FROM PRODUCTION_DB.PUBLIC.BI_LOAN bi
JOIN PRODUCTION_DB.PUBLIC.CREDIT_SUISSE_FEED cs ON cs.LOAN_NUMBER = bi.LOAN_ID AND cs.REPORT_DATE = DATEADD(Day ,-2, current_date)
JOIN PRODUCTION_DB.PUBLIC.PARTNER_CLASSIFICATION pc USING(UPCODE)
WHERE loan_status NOT IN ('Not Originated', 'Cancelled')
