SELECT
LOAN_ID,
ccsp_invoice_date AS REPORT_DATE,
CASE 
  WHEN DEBIT_CREDIT_CODE = 'DB'
  THEN FORM_OF_PAYMENT_AMOUNT / 100
  ELSE -1 * FORM_OF_PAYMENT_AMOUNT / 100
END AS AMOUNT,
'uatp' AS PROCESSOR
FROM production_db.PUBLIC.atcan_transactions
