SELECT
LOAN_ID,
POSTING_DATE AS REPORT_DATE,
AMOUNT,
PAYMENT_PROCESSOR AS PROCESSOR
FROM PRODUCTION_DB.PUBLIC.BI_DISBURSEMENT disb
LEFT JOIN PRODUCTION_DB.PUBLIC.BI_LOAN bi 
  ON disb.APPLICATION_ID = bi.APPLICATIONID
WHERE PAYMENT_PROCESSOR NOT IN ('uatp')
